### PR TITLE
Add support for ARM64 linux running on MacOS arm container

### LINKED ISSUE #5: Can't install on Docker on MacOS with arm processor
**Describe the bug**

When trying to install in a container running on MacOS with arm processor (M1/M2) I get the following error:

```
/path/to/.asdf/plugins/gitleaks/lib/utils.bash: line 64: arch: unbound variable
```

**Steps to reproduce**

1. Open a linux container in Docker Desktop/Rancher desktop on MacOS with M1/M2 processor
2. Try to install gitleaks
3. Get the following error instead:
   ```
   /path/to/.asdf/plugins/gitleaks/lib/utils.bash: line 64: arch: unbound variable
   ```

**Expected behavior**

It should install

**Additional context**

It seems the `arch` variable comes from the output of running `uname -m`. In a linux container running an arm64 version of linux, the output is `aarch64`

### PR DESCRIPTION
**Pull request by brodock**
Fixes https://github.com/jmcvetta/asdf-gitleaks/issues/5

### CODE REVIEW

**Review by nelsnelson — CHANGES_REQUESTED** [review]
You might also be able to combine the cases like:

    aarch64|arm*)
      arch="arm64"
      ;;

**Comment by nelsnelson** [comment]
Hi @jmcvetta , I was wondering if this patch could be merged as soon as possible.  The bug it fixes is blocking me.

My comment being addressed is not required and can be dismissed if it accelerates acceptance.

**Review by jmcvetta — APPROVED** [review]

**Review by jmcvetta — APPROVED** [review]

**Comment by jmcvetta** [comment]
Hi @nelsnelson - thanks for the contribution!  Your PR has been merged and included in release 1.1.0.

**Comment by nelsnelson** [comment]
> Hi @nelsnelson - thanks for the contribution! Your PR has been merged and included in release 1.1.0.

Oh, thank you!  Although, this patch work was not submitted by myself, but rather submitted by @brodock!

Cheers!

**Comment by jmcvetta** [comment]
My mistake - thanks to @brodock for contributing this!

**Pull request merged**
